
import { Event } from "@/types";

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Annual Cultural Festival",
    description: "Join us for a celebration of cultural diversity with performances, food stalls, and art exhibitions from around the world. This annual event brings together students from various backgrounds to showcase their traditions and talents.\n\nActivities include dance performances, musical shows, traditional costume displays, international cuisine, and much more. Don't miss this opportunity to experience a global journey right on campus!",
    date: "2023-12-15",
    time: "14:00",
    venue: "College Auditorium",
    category: "Cultural",
    organizer: "Cultural Committee",
    registrationLink: "https://forms.google.com/cultural-fest",
    imageUrl: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=2070&auto=format&fit=crop",
    featured: true,
    createdAt: "2023-11-20T08:00:00Z",
  },
  {
    id: "2",
    title: "Tech Symposium 2023",
    description: "A two-day event featuring workshops, talks, and competitions on the latest technological trends. Experts from leading tech companies will share insights on AI, blockchain, cybersecurity, and more.",
    date: "2023-12-10",
    time: "09:00",
    venue: "Engineering Block",
    category: "Academic",
    organizer: "Computer Science Department",
    registrationLink: "https://forms.google.com/tech-symposium",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=2070&auto=format&fit=crop",
    featured: true,
    createdAt: "2023-11-15T10:30:00Z",
  },
  {
    id: "3",
    title: "Annual Sports Meet",
    description: "Competitive sports events including football, basketball, tennis, and athletics. Open to all students and faculty members.",
    date: "2023-12-05",
    time: "08:30",
    venue: "College Sports Complex",
    category: "Sports",
    organizer: "Sports Committee",
    registrationLink: "https://forms.google.com/sports-meet",
    imageUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=2070&auto=format&fit=crop",
    featured: false,
    createdAt: "2023-11-10T12:45:00Z",
  },
  {
    id: "4",
    title: "Career Fair 2023",
    description: "Connect with recruiters from top companies across various industries. Bring your resume and dress professionally for on-the-spot interviews.",
    date: "2023-12-20",
    time: "10:00",
    venue: "College Convention Center",
    category: "Workshop",
    organizer: "Placement Cell",
    registrationLink: "https://forms.google.com/career-fair",
    imageUrl: "https://images.unsplash.com/photo-1540317580384-e5d43867caa6?q=80&w=2070&auto=format&fit=crop",
    featured: false,
    createdAt: "2023-11-25T09:15:00Z",
  },
  {
    id: "5",
    title: "Photography Workshop",
    description: "Learn the fundamentals of photography from professional photographers. Bring your camera if you have one.",
    date: "2023-12-08",
    time: "15:00",
    venue: "Art Building, Room 102",
    category: "Workshop",
    organizer: "Photography Club",
    registrationLink: "https://forms.google.com/photo-workshop",
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=1964&auto=format&fit=crop",
    featured: false,
    createdAt: "2023-11-12T14:20:00Z",
  },
  {
    id: "6",
    title: "Debate Competition",
    description: "Annual inter-college debate competition on current social and political issues. Teams of two can participate.",
    date: "2023-12-12",
    time: "13:00",
    venue: "Humanities Lecture Hall",
    category: "Competition",
    organizer: "Literary Society",
    registrationLink: "https://forms.google.com/debate-comp",
    imageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=2070&auto=format&fit=crop",
    featured: false,
    createdAt: "2023-11-18T11:10:00Z",
  },
  {
    id: "7",
    title: "Alumni Meetup",
    description: "Annual gathering of college alumni to network, share experiences, and mentor current students.",
    date: "2023-12-18",
    time: "17:00",
    venue: "College Banquet Hall",
    category: "General",
    organizer: "Alumni Association",
    registrationLink: "https://forms.google.com/alumni-meetup",
    imageUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?q=80&w=2070&auto=format&fit=crop",
    featured: false,
    createdAt: "2023-11-22T16:40:00Z",
  },
  {
    id: "8",
    title: "Hackathon: Code for Change",
    description: "24-hour coding challenge to develop solutions for community problems. Open to all students with coding experience.",
    date: "2023-12-22",
    time: "18:00",
    venue: "Computer Science Lab",
    category: "Competition",
    organizer: "Coding Club",
    registrationLink: "https://forms.google.com/hackathon",
    imageUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=2070&auto=format&fit=crop",
    featured: true,
    createdAt: "2023-11-28T08:50:00Z",
  },
];
