// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxkfdfszkerzwwoeqdvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4a2ZkZnN6a2Vyend3b2VxZHZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDk3NDgsImV4cCI6MjA1ODkyNTc0OH0.4iXwDNa93ydbmT73Kd7vkT3wY4Ui8XXKF_m2r5Wh4Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);